package com.jobportal.service;
import com.jobportal.dto.UserDtos; import com.jobportal.entity.*; import com.jobportal.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional public class ApplicationService { private final ApplicationRepository apps; private final JobRepository jobs; private final UserRepository users; private final UserService userService; public ApplicationService(ApplicationRepository apps, JobRepository jobs, UserRepository users, UserService userService){this.apps=apps;this.jobs=jobs;this.users=users;this.userService=userService;}
 public UserDtos.ApplicationResponse apply(Long jobId,User u){var j=jobs.findById(jobId).orElseThrow(()->new IllegalArgumentException("Job not found"));if(!j.isActive())throw new IllegalArgumentException("Job is closed");if(j.getApprovalStatus()!=Job.ApprovalStatus.APPROVED)throw new IllegalArgumentException("Job is not approved yet");if(j.isPremium()&&!userService.isPremium(u.getId()))throw new IllegalArgumentException("Premium subscription required");if(apps.existsByJobIdAndUserId(jobId,u.getId()))throw new IllegalArgumentException("Already applied");var a=apps.save(new Application(null,j,u,null,null));return response(a);}
 @Transactional(readOnly = true) public List<UserDtos.ApplicationResponse> byUser(Long id){return apps.findByUserIdOrderByAppliedAtDesc(id).stream().map(this::response).toList();} @Transactional(readOnly = true) public List<UserDtos.ApplicationResponse> byRecruiter(Long id){return apps.findByJobRecruiterIdOrderByAppliedAtDesc(id).stream().map(this::response).toList();}
 public UserDtos.ApplicationResponse status(Long id,String status,User recruiter){var a=apps.findById(id).orElseThrow(()->new IllegalArgumentException("Application not found"));if(!a.getJob().getRecruiter().getId().equals(recruiter.getId()))throw new IllegalArgumentException("Not your application");a.setStatus(Application.Status.valueOf(status.toUpperCase()));return response(apps.save(a));}
 public UserDtos.ApplicationResponse response(Application a){return new UserDtos.ApplicationResponse(a.getId(),a.getJob().getId(),a.getJob().getTitle(),a.getJob().getCompany(),a.getJob().getLocation(),a.getStatus().name(),a.getAppliedAt().toString(),a.getUser().getId(),a.getUser().getName(),a.getUser().getProfileImageUrl(),null);}
 @Transactional(readOnly = true) public List<UserDtos.ApplicationResponse> all(){return apps.findAll().stream().map(this::response).toList();}
 public long count(){return apps.count();} public long statusCount(Application.Status s){return apps.countByStatus(s);}
}
