package com.jobportal.service;
import com.jobportal.dto.JobDtos; import com.jobportal.entity.*; import com.jobportal.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional public class JobService { private final JobRepository jobs; private final UserRepository users; private final CompanyRepository companies; public JobService(JobRepository jobs,UserRepository users,CompanyRepository companies){this.jobs=jobs;this.users=users;this.companies=companies;}
 public Job save(JobDtos.JobRequest r,User recruiter){Job j=new Job(null,r.title(),r.company(),r.location(),r.employmentType(),r.minSalary(),r.maxSalary(),r.experienceRequired(),r.qualification(),r.description(),r.skills(),r.premium(),true,null,recruiter);if(r.companyId()!=null)j.setCompanyEntity(companies.findById(r.companyId()).filter(Company::isApproved).orElseThrow(()->new IllegalArgumentException("Company ID not found or not approved")));return jobs.save(j);}
 public Job update(Long id,JobDtos.JobRequest r,User recruiter){var j=get(id);if(!j.getRecruiter().getId().equals(recruiter.getId()))throw new IllegalArgumentException("Not your job");j.setTitle(r.title());j.setCompany(r.company());j.setLocation(r.location());j.setEmploymentType(r.employmentType());j.setMinSalary(r.minSalary());j.setMaxSalary(r.maxSalary());j.setExperienceRequired(r.experienceRequired());j.setQualification(r.qualification());j.setDescription(r.description());j.setSkills(r.skills());j.setPremium(r.premium());if(r.companyId()!=null)j.setCompanyEntity(companies.findById(r.companyId()).filter(Company::isApproved).orElseThrow(()->new IllegalArgumentException("Company ID not found or not approved")));else j.setCompanyEntity(null);j.setApprovalStatus(Job.ApprovalStatus.PENDING);j.setActive(false);j.setRejectionReason(null);j.setAdminNote(null);return jobs.save(j);}
 @Transactional(readOnly=true) public Job get(Long id){return jobs.findById(id).orElseThrow(()->new IllegalArgumentException("Job not found"));}
 public void verifyRecruiterOwnsJob(Long jobId,Long recruiterId){var j=get(jobId);if(j.getRecruiter()==null||!j.getRecruiter().getId().equals(recruiterId))throw new IllegalArgumentException("You can only view comments for your own jobs");}
 @Transactional(readOnly=true) public List<Job> publicJobs(){return jobs.findByActiveTrueAndApprovalStatusOrderByPostedAtDesc(Job.ApprovalStatus.APPROVED);} @Transactional(readOnly=true) public List<Job> search(String q,String company,String location){if((q==null||q.isBlank())&&(company==null||company.isBlank())&&(location==null||location.isBlank()))return publicJobs();return jobs.search(q==null?"":q,company==null?"":company,location==null?"":location);}
 @Transactional(readOnly=true) public List<Job> recruiterJobs(Long id){return jobs.findByRecruiterIdOrderByPostedAtDesc(id);} public void delete(Long id,User r){var j=get(id);if(!j.getRecruiter().getId().equals(r.getId()))throw new IllegalArgumentException("Not your job");jobs.delete(j);}
 @Transactional(readOnly=true) public JobDtos.JobResponse response(Job j){Company c=j.getCompanyEntity();return new JobDtos.JobResponse(j.getId(),j.getTitle(),j.getCompany(),j.getLocation(),j.getEmploymentType(),j.getMinSalary(),j.getMaxSalary(),j.getExperienceRequired(),j.getQualification(),j.getDescription(),j.getSkills(),j.isPremium(),j.isActive(),j.getPostedAt()==null?null:j.getPostedAt().toString(),j.getRecruiter().getId(),j.getRecruiter().getName(),j.getRecruiter().getProfileImageUrl(),j.getApprovalStatus()==null?"PENDING":j.getApprovalStatus().name(),j.getAdminNote(),j.getRejectionReason(),c==null?null:c.getId(),c==null?null:c.getDescription(),c==null?null:c.getWebsite(),c==null?null:c.getLocation(),c==null?null:c.getImageUrl());}
 public long count(){return jobs.count();} public long activeCount(){return jobs.countByActiveTrueAndApprovalStatus(Job.ApprovalStatus.APPROVED);}
}
