package com.jobportal.service;
import com.jobportal.dto.UserDtos; import com.jobportal.entity.*; import com.jobportal.repository.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*;
@Service public class UserService { private final UserRepository users; private final PasswordEncoder encoder; private final PremiumSubscriptionRepository subs; private final CompanyRepository companies; public UserService(UserRepository users, PasswordEncoder encoder, PremiumSubscriptionRepository subs, CompanyRepository companies){this.users=users;this.encoder=encoder;this.subs=subs;this.companies=companies;}
 public User register(com.jobportal.dto.AuthDtos.RegisterRequest r,User.Role role){if(users.existsByEmail(r.email()))throw new IllegalArgumentException("Email already registered");User u=new User(null,r.name(),r.email(),r.phoneNumber(),r.age(),r.experience(),r.address(),r.qualification(),null,encoder.encode(r.password()),role,null); if(role==User.Role.RECRUITER && r.companyId()!=null){u.setCompany(companies.findById(r.companyId()).filter(Company::isApproved).orElseThrow(()->new IllegalArgumentException("Company ID not found or not approved")));} return users.save(u);}
 public User get(Long id){return users.findById(id).orElseThrow(()->new IllegalArgumentException("User not found"));}
 @Transactional(readOnly=true) public UserDtos.UserResponse response(User u){return new UserDtos.UserResponse(u.getId(),u.getName(),u.getEmail(),u.getPhoneNumber(),u.getAge(),u.getExperience(),u.getAddress(),u.getQualification(),u.getRole().name(),isPremium(u.getId()),u.getProfileImageUrl(),u.getCompany()==null?null:u.getCompany().getId(),u.getCompany()==null?null:u.getCompany().getName());}
 public boolean isPremium(Long id){return subs.findByUserId(id).map(PremiumSubscription::active).orElse(false);}
 public UserDtos.UserResponse update(Long id,UserDtos.ProfileRequest r, String profileImageUrl){var u=get(id);if(r.name()!=null)u.setName(r.name());if(r.phoneNumber()!=null)u.setPhoneNumber(r.phoneNumber());u.setAge(r.age());u.setExperience(r.experience());u.setAddress(r.address());u.setQualification(r.qualification());if(profileImageUrl!=null)u.setProfileImageUrl(profileImageUrl);return response(users.save(u));}
 public UserDtos.UserResponse subscribe(Long id,UserDtos.SubscriptionRequest r){var u=get(id);int months=r.months()>0?r.months():1;var plan=PremiumSubscription.Plan.valueOf(r.plan().toUpperCase());var existing=subs.findByUserId(id).orElse(null);LocalDate start=existing!=null&&existing.active()?existing.getEndDate().plusDays(1):LocalDate.now();LocalDate end=start.plusMonths(months).minusDays(1);subs.save(new PremiumSubscription(existing==null?null:existing.getId(),u,start,end,plan));return response(u);}
}
