package com.jobportal.entity;
import jakarta.persistence.*; import java.time.LocalDateTime;
@Entity @Table(name="jobs") public class Job {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id; @Column(nullable=false) private String title; @Column(nullable=false) private String company; @Column(nullable=false) private String location; private String employmentType; private Double minSalary; private Double maxSalary; private String experienceRequired; private String qualification; @Column(length=4000) private String description; @Column(length=3000) private String skills; private boolean premium; private boolean active; private LocalDateTime postedAt; @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="recruiter_id",nullable=false) private User recruiter;
 @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="company_id") private Company companyEntity;
 @Enumerated(EnumType.STRING) @Column(name="approval_status") private ApprovalStatus approvalStatus;
 @Column(length=1000) private String adminNote;
 @Column(length=1000) private String rejectionReason;
 public Job(){} public Job(Long id,String title,String company,String location,String employmentType,Double minSalary,Double maxSalary,String experienceRequired,String qualification,String description,String skills,boolean premium,boolean active,LocalDateTime postedAt,User recruiter){this.id=id;this.title=title;this.company=company;this.location=location;this.employmentType=employmentType;this.minSalary=minSalary;this.maxSalary=maxSalary;this.experienceRequired=experienceRequired;this.qualification=qualification;this.description=description;this.skills=skills;this.premium=premium;this.active=active;this.postedAt=postedAt;this.recruiter=recruiter;this.approvalStatus=ApprovalStatus.PENDING;}
 @PrePersist void prePersist(){postedAt=LocalDateTime.now();if(approvalStatus==null)approvalStatus=ApprovalStatus.PENDING;if(approvalStatus!=ApprovalStatus.APPROVED)active=false;}
 public Long getId(){return id;} public void setId(Long v){id=v;} public String getTitle(){return title;} public void setTitle(String v){title=v;} public String getCompany(){return company;} public void setCompany(String v){company=v;} public String getLocation(){return location;} public void setLocation(String v){location=v;} public String getEmploymentType(){return employmentType;} public void setEmploymentType(String v){employmentType=v;} public Double getMinSalary(){return minSalary;} public void setMinSalary(Double v){minSalary=v;} public Double getMaxSalary(){return maxSalary;} public void setMaxSalary(Double v){maxSalary=v;} public String getExperienceRequired(){return experienceRequired;} public void setExperienceRequired(String v){experienceRequired=v;} public String getQualification(){return qualification;} public void setQualification(String v){qualification=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public String getSkills(){return skills;} public void setSkills(String v){skills=v;} public boolean isPremium(){return premium;} public void setPremium(boolean v){premium=v;} public boolean isActive(){return active;} public void setActive(boolean v){active=v;} public LocalDateTime getPostedAt(){return postedAt;} public void setPostedAt(LocalDateTime v){postedAt=v;} public User getRecruiter(){return recruiter;} public void setRecruiter(User v){recruiter=v;} public Company getCompanyEntity(){return companyEntity;} public void setCompanyEntity(Company v){companyEntity=v;} public ApprovalStatus getApprovalStatus(){return approvalStatus;} public void setApprovalStatus(ApprovalStatus v){approvalStatus=v;} public String getAdminNote(){return adminNote;} public void setAdminNote(String v){adminNote=v;} public String getRejectionReason(){return rejectionReason;} public void setRejectionReason(String v){rejectionReason=v;} public enum ApprovalStatus { APPROVED, PENDING, REJECTED }
}
